In [2]:
""" Imports and Path Setup """
%load_ext autoreload
%autoreload 2

import sys
import os

root = os.path.abspath("..")
if root not in sys.path:
    sys.path.insert(0, root)


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from src.data_loader import *

In [3]:
"""Load Raw Data"""

df_raw=load_raw_data()

print(f"Raw Data Shape: {df_raw.shape}")

Raw Data Shape: (5001, 21)

In [4]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 5001 entries, 0 to 5000
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5001 non-null   str
 1   gender             5001 non-null   str
 2   senior_citizen     5001 non-null   int64
 3   partner            5001 non-null   str
 4   dependents         4801 non-null   str
 5   tenure_months      5001 non-null   int64
 6   phone_service      5001 non-null   str
 7   multiple_lines     5001 non-null   str
 8   internet_service   5001 non-null   str
 9   online_security    5001 non-null   str
 10  online_backup      5001 non-null   str
 11  device_protection  5001 non-null   str
 12  tech_support       5001 non-null   str
 13  streaming_tv       5001 non-null   str
 14  streaming_movies   5001 non-null   str
 15  contract_type      5001 non-null   str
 16  paperless_billing  5001 non-null   str
 17  payment_method     4851 non-null   str
 18  monthly_charges    5001 non-null   float64
 19  total_charges      5001 non-null   str
 20  churn              5001 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.3 MB

In [5]:
df_raw['total_charges'].isna().sum()

np.int64(0)

In [6]:
df=df_raw.copy()

In [7]:
df['payment_method'].isna().sum()

np.int64(150)

In [8]:
df["total_charges"].values.dtype

In [9]:
df.head()

,customer_id,gender,senior_citizen,partner,dependents,tenure_months,phone_service,multiple_lines,internet_service,online_security,...,device_protection,tech_support,streaming_tv,streaming_movies,contract_type,paperless_billing,payment_method,monthly_charges,total_charges,churn
0,CUST-00005,Male,0,Yes,Yes,53,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Electronic check,29.29,1553.16,No
1,CUST-00001,Male,0,No,Yes,61,Yes,No,Fiber optic,Yes,...,No,No,No,No,Month-to-month,No,Credit card,87.04,5303.45,No
2,CUST-00002,Female,0,No,No,68,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Credit card,28.63,1944.52,No
3,CUST-00003,Male,0,No,NaN,62,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Credit card,27.85,1736.17,No
4,CUST-00004,Male,1,Yes,No,1,Yes,Yes,DSL,No,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,67.92,62.16,Yes

In [10]:
df["total_charges"]=pd.to_numeric(df["total_charges"], errors='coerce')

In [11]:
df[['senior_citizen','payment_method']].value_counts()

senior_citizen  payment_method
0               Electronic check    1418
                Mailed check        1012
                Bank transfer        867
                Credit card          849
1               Electronic check     248
                Mailed check         182
                Credit card          142
                Bank transfer        133
Name: count, dtype: int64

In [12]:
df['senior_citizen']= df['senior_citizen'].map({0:'No',1:'Yes'})

In [13]:
df.head()

,customer_id,gender,senior_citizen,partner,dependents,tenure_months,phone_service,multiple_lines,internet_service,online_security,...,device_protection,tech_support,streaming_tv,streaming_movies,contract_type,paperless_billing,payment_method,monthly_charges,total_charges,churn
0,CUST-00005,Male,No,Yes,Yes,53,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Electronic check,29.29,1553.16,No
1,CUST-00001,Male,No,No,Yes,61,Yes,No,Fiber optic,Yes,...,No,No,No,No,Month-to-month,No,Credit card,87.04,5303.45,No
2,CUST-00002,Female,No,No,No,68,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Credit card,28.63,1944.52,No
3,CUST-00003,Male,No,No,NaN,62,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Credit card,27.85,1736.17,No
4,CUST-00004,Male,Yes,Yes,No,1,Yes,Yes,DSL,No,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,67.92,62.16,Yes

In [14]:
mask1=df['total_charges'].isna()
df.loc[mask1,'total_charges']=0.0

In [15]:
df['total_charges'].isna().sum()
df['dependents'].isna().sum()

np.int64(200)

In [16]:
df['payment_method'].isna().sum()

np.int64(150)

In [17]:
mode=df['dependents'].mode()[0]
mask2=df['dependents'].isna()
df.loc[mask2,'dependents']=mode

In [18]:
mask4=df.duplicated()
df=df.drop_duplicates(keep='first')
df.duplicated().sum()

np.int64(0)

In [23]:
df['contract_type'].value_counts()

contract_type
Month-To-Month    2867
Two Year          1171
One Year           962
Name: count, dtype: int64

In [22]:
df['contract_type'] = (
    df['contract_type']
    .str.strip()
    .str.lower()
    .str.title()
)